[package]
name = "simd_rand"
version = "0.1.0"
edition = "2021"

[profile.release]
panic = "abort"
lto = true
opt-level = 3
debug = 2
codegen-units = 1

[dependencies]
rand_core = "0.6"

[dev-dependencies]
rand = { version = "0.8", features = ["small_rng"] }
num-traits = "0.2"
dhat = "0.3.2"
criterion = { version = "0.5", features = ["html_reports"] }
criterion-perf-events = "0.4"
perfcnt = "0.8"
itertools = "0.11.0"
rand_xoshiro = "0.6.0"
serial_test = "2.0.0"
rust_decimal = { version = "1.30.0", features = ["maths"] }
rust_decimal_macros = "1.30.0"

[lib]
bench = false

[[bench]]
name = "main"
harness = false

[[example]]
name = "dasm"
path = "examples/_internal/dasm.rs"
bench = false

[[example]]
name = "profile"
path = "examples/_internal/profile.rs"
bench = false
