[package]
name = "shishua"
version = "0.1.0"
edition = "2021"

[profile.release]
panic = "abort"
lto = true
opt-level = 3
debug = 2
codegen-units = 1

[dependencies]
rand_core = "0.6"
rand = { version = "0.8", features = ["small_rng"] }

[dev-dependencies]
num-traits = "0.2"
dhat = "0.3.2"
criterion = { version = "0.5", features = ["html_reports"] }

[lib]
bench = false

[[bench]]
name = "rng"
harness = false

[[bin]]
name = "dasm"
path = "src/bin/dasm.rs"
bench = false

[[bin]]
name = "profile"
path = "src/bin/profile.rs"
bench = false
